server:
  servlet:
    context-path: /
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/busData?characterEncoding=utf8&useSSL=false
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #按字段名字建表
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false

  messages:
    basename: myconfig

  cache:
    redis:
      time-to-live: 60s
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456@abc.com
    timeout: 10000
    lettuce:
      pool:
        max-idle: 10
        max-active: 10
        min-idle: 5
        max-wait: 10000
    database: 0





